apiVersion: infrastructure.cluster.x-k8s.io/v1alpha2
kind: MetalMachine
metadata:
  name: controlplane-0
spec:
  serverRef:
    apiVersion: metal.arges.dev/v1alpha1
    kind: Server
    name: '00000000-0000-0000-0000-d05099d4c8ed'
  bmc:
    endpoint: '192.168.1.100'
    user: 'admin'
    pass: 'admin'
---
apiVersion: cluster.x-k8s.io/v1alpha2
kind: Machine
metadata:
  labels:
    cluster.x-k8s.io/cluster-name: example-0
    cluster.x-k8s.io/control-plane: 'true'
  name: controlplane-0
spec:
  bootstrap:
    configRef:
      apiVersion: bootstrap.cluster.x-k8s.io/v1alpha2
      kind: TalosConfig
      name: controlplane-0
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha2
    kind: MetalMachine
    name: controlplane-0
  version: 1.17.3
